# -*- coding: utf-8 -*-
"""
/***************************************************************************
 climaplots
                                 A QGIS plugin
 Climate Trend Data and Analysis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-11-15
        copyright            : (C) 2022 by Caio Arantes
        contact              : github/caioarantes
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load climaplots class from file clima_plots.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .clima_plots import climaplots
    return climaplots(iface)
